import numpy as np
import matplotlib.pyplot as plt
vec1 = np.array ([-1. , 4. , -9.])
mat1 = np.array ([[1. , 3. , 5.], [7. , -9. , 2.], [4. , 6. , 8.]])
vec2 = (np.pi/4)* vec1
print ('vec2 is: ', vec2)
vec2 = np.cos (vec2)
print ('cos vec1 is: ', vec2)
vec3 = vec1 + 2 * vec2
print ('vec3 is : ', vec3)
vec4 = np.dot (mat1 , vec3)
print ('Matrix product of mat1 and vec3 is: ', vec4)
print ('transpose of mat1 is: ', np.transpose(mat1))
print ('mat1 determinant is: ', np.linalg.det (mat1))
print ('mat1trace is:', np.trace (mat1))
print ('The smallest element in vec1 is: ', np.min(vec1))
print ('The position of smallest element in vec1 is:', np.where(np.min(vec1)))
print ('the smalest element in mat1 is: ', np.min(mat1))
A = np.array([[17 , 24 , 1, 8 , 15], [23 , 5 , 7 , 14 , 16] , 
              [4 , 6 , 13 , 20 , 22], [10 , 12, 19 , 21 , 3] ,
              [11 , 18 , 25 , 2 , 9]])
print ('sum of elements in row NO. 1 is: ', np.sum(A[0, :]))
print ('sum of elements in row NO. 2 is: ', np.sum(A[1, :]))
print ('sum of elements in row NO. 3 is: ', np.sum(A[2, :]))
print ('sum of elements in row NO. 4 is: ', np.sum(A[3, :]))
print ('sum of elements in row NO. 5 is: ', np.sum(A[4, :]))
print ('sum of elements in column NO. 1 is: ', np.sum(A[:, 0]))
print ('sum of elements in column NO. 1 is: ', np.sum(A[:, 1]))
print ('sum of elements in column NO. 1 is: ', np.sum(A[:, 2]))
print ('sum of elements in column NO. 1 is: ', np.sum(A[:, 3]))
print ('sum of elements in column NO. 1 is: ', np.sum(A[:, 4]))
print ('sum of elements in diogonal of A  is: ', np.sum(np.diag (A)))
print ('sum of elements in other diogonal of A  is: ', np.sum(np.diag(np.fliplr (A))))
M = np.random.rand(10 ,10)
print ('The random 10*10 matrix is: ', M)
print ('The upper left sub_matrix is: ',  M[0:5 , 0:5])
print ('The upper roght sub_matrix is: ',  M[0:5 , 5:10])
print ('The lower left sub_matrix is: ',  M[5:10 , 0:5])
print ('The lower right sub_matrix is: ',  M[5:10 , 5:10])
