import numpy as np
import matplotlib.pyplot as plt
x = np.linspace (0 ,10)
f_x = np.exp(-x/10)*np.sin(np.pi*x)
g_x = x* np.exp(-x/3)
fig, ax=plt.subplots()
ax.plot(x, f_x , label='f(x)')
ax.plot (x, g_x , label = 'g(x)')
leg = ax.legend()
plt.xlabel ('x')
plt.ylabel('y')
plt.show()
teta = np.linspace (0 , 2*np.pi)
r_8 = 0.8 + np.cos (teta)
r_1 = 1.0 + np.cos (teta)
r_2 = 1.2 + np.cos (teta)
x_8 = r_8 * np.cos (teta)
y_8 = r_8 * np.sin (teta)
x_1 = r_1 * np.cos (teta)
y_1 = r_1 * np.sin (teta)
x_2 = r_2 * np.cos (teta)
y_2 = r_2 * np.sin (teta)
fig, ay =plt.subplots()
ay.plot(x_8 , y_8 , label = 'r=0.8')
ay.plot(x_1 , y_1 , label = 'r=1.0')
ay.plot(x_2 , y_2 , label = 'r=1.2')
leg1 = ay.legend()
plt.xlabel ('x')
plt.ylabel('y')
plt.show()
